root: /

Home: /

language: en

author: iGuan7u
description: A beautiful & simple theme.


# AvatorURL
# it would be shown on sidecar.

avatar: https://avatars0.githubusercontent.com/u/5751958?s=460&u=78c700a9964e592b6d218bb67896c8eddc6954c8&v=4

# Comment

gitalk:
  enable: false
  clientID: github_clientID
  clientSecret: github_clientSecret
  repo: you site homepage
  owner: your username
  admin: same as [owner]

disqus:
  enable: false
  shortname: your_disqus_short_name

# Contact_Info
# Contact info will be shown on the side bar.

contact:
  enable: true
  description: ''

  twitter:
    enable: false
    username: twitter_username

  github:
    enable: true
    username: caoyangyang

  weibo:
    enable: false
    username: weibo_username

  facebook:
    enable: true
    username: yangyang.jane.cao

  instagram:
    enable: false
    username: instagram_username


# Analytice

mta_analytics:
  enable: false
  name: mta_analytics_name
  sid: mta_analytics_sid

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: true
  content: "鄂ICP备19027332号-1"

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false